version: '3.8'
services:
  shop:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop
    volumes:
      - shop:/var/lib/postgresql/data
    ports:
      - '5435:5432'

volumes:
  shop:
