version: '3.8'
services:
  db:
    restart: always
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5434'
